# Generated by Django 4.0.2 on 2022-02-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miniblog',
            options={'ordering': ['created']},
        ),
    ]
